name: CI

on:
  push:
    branches:
      - main
  pull_request:


jobs:
  test:
    strategy:
      matrix:
        demo:
          - demos/features/01-pages
          - demos/pipelines/01-simple-rating
          - demos/pipelines/02-tapping
          - demos/pipelines/03-step-tag
          - demos/pipelines/04-similarity
          - demos/pipelines/05-timed-push-buttons
    runs-on: ubuntu-latest
    name: Test ${{ matrix.demo }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Run tests in dev container
        uses: devcontainers/ci@v0.3
        with:
          runCmd: pytest ${{ matrix.demo }}/test.py
          push: never

